name: Build-SQLite-Docker-Only

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:  # 允许手动触发

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main-sqlite

      - name: Get version
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARMv7 image (no push)
        run: |
          # 仅构建不推送，镜像保留在构建缓存中
          docker buildx build \
            --platform linux/arm/v7 \
            --tag dingdangdog/cashbook:${VERSION}-armv7-sqlite .
